[BUILD] Update version of datasource-list to 1.1.0
digital-enabler/UI-Configs pull request #132
Opened 2023-04-18 10:40 UTC by Dnikodij

2023-04-18 14:09 UTC, imolnar92 approved these changes

2023-04-19 10:17 UTC, imolnar92 requested changes

2023-04-19 15:31 UTC, sirnino commented on mf-dev/dme/dme-import-map.json
> +    "@digital-enabler/mashups-list": "https://cdn.jsdelivr.net/npm/@digital-enabler/mashups-list@1.1.3/app.js",
Changes like these are "tricky" to version. I would say that it's a minor release so `1.1.0` (not `1.1.3`: everytime you change a minor version the patch version goes to 0)

2023-04-20 09:34 UTC, imolnar92 approved these changes

2023-04-27 08:53 UTC, merged